services:
  PhpList\Core\Domain\Service\Validator\TemplateLinkValidator:
    autowire: true
    autoconfigure: true

  PhpList\Core\Domain\Service\Validator\TemplateImageValidator:
    autowire: true
    autoconfigure: true
