services:
  PhpList\Core\Domain\Subscription\Validator\TemplateLinkValidator:
    autowire: true
    autoconfigure: true

  PhpList\Core\Domain\Subscription\Validator\TemplateImageValidator:
    autowire: true
    autoconfigure: true
