services:

  Admin:
    class: phpList\Admin
    arguments: ["@AdminModel", "@Pass"]
  LoggerWriterAbstractFactory:
    class: phpList\helper\Logger\LoggerWriterAbstractFactory
    arguments: ["@Config"]
  Logger:
    class: phpList\helper\Logger
    arguments: ["@LoggerWriterAbstractFactory"]
  Util:
    class: phpList\helper\Util
    arguments: ["@Config", "@Logger", "@Database"]
  EmailAddress:
    class:  phpList\EmailAddress
    arguments: ["@Config", %emailaddress.address%]
  EmailUtil:
    class:  phpList\EmailUtil
  Config:
    class: phpList\Config
    arguments: [%config.configfile%]
  Database:
    class:  phpList\helper\Database
    arguments: ["@Config"]
  Language:
    class: phpList\helper\Language
    arguments: ["@Database", "@Config"]
  Pass:
    class: phpList\Pass
    arguments: ["@Config"]
  phpList:
    class: phpList\phpList
    arguments: ["@Config", "@Database", "@Language", "@Util"]
  Campaign:
    class: phpList\Campaign
    arguments: ["@Config", "@Database", "@MailingList", "@Template"]
  Template:
    class: phpList\Template
    arguments: ["@Config", "@Database", "@TemplateImage"]
  TemplateImage:
    class: phpList\TemplateImage
    arguments: ["@Config", "@Database"]

# Entities
  CampaignEntity:
    class: phpList\Entity\CampaignEntity
  ListEntity:
    class: phpList\Entity\ListEntity
  SubscriberEntity:
    class: phpList\Entity\SubscriberEntity
  TemplateEntity:
    class: phpList\Entity\TemplateEntity
  TemplateImageEntity:
    class: phpList\Entity\TemplateImageEntity

# Managers
  ListManager:
    class: phpList\ListManager
    arguments: ["@Config", "@Database", "@ListModel"]
  SubscriberManager:
    class: phpList\SubscriberManager
    arguments: ["@Config", "@EmailUtil", "@Pass", "@SubscriberModel"]

# Models
  AdminModel:
    class: phpList\Model\AdminModel
    arguments: ["@Config", "@Database"]
  ListModel:
    class: phpList\Model\ListModel
    arguments: ["@Config", "@Database"]
  SubscriberModel:
    class: phpList\Model\SubscriberModel
    arguments: ["@Config", "@Database"]

# Define parameters, to be set in app logic
# NOTE: the classname.parameter syntax is just a Symfony convention; parameter
# names are handles as single simple strings
parameters:
  config.configfile: null
  emailaddress.address: emailaddress
  password.password: password
