imports:
    - { resource: config.yml }

monolog:
    handlers:
        # Primary handler for production is Graylog
#        graylog:
#            type: gelf
#            publisher:
#                hostname: '%graylog_host%'
#                port: '%graylog_port%'
#            level: error
        # Local file logging as backup
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
