# Doctrine Configuration
doctrine:
  dbal:
    # These variables come from parameters.yml. There, the values are read from environment variables
    # and can also be set directly in the parameters.yml file.
    driver: '%database_driver%'
    host: '%database_host%'
    path: '%database_path%'
    port: '%database_port%'
    dbname: '%database_name%'
    user: '%database_user%'
    password: '%database_password%'
    charset: UTF8

  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      PhpList\Core\Domain\Model:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Domain/Model/'
        prefix: 'PhpList\Core\Domain\Model\'
    controller_resolver:
      auto_mapping: false
