imports:
  - { resource: "../Services.yml" }

framework:
  profiler: { only_exceptions: false }
  secret: d9c7e737bdb920e1d10df3588a3941782b905361
  router:
    resource: '%kernel.project_dir%/Configuration/Environments/routing_dev.yml'
    strict_requirements: true
