imports:
  - { resource: "services.yml" }

framework:
  secret: d9c7e737bdb920e1d10df3588a3941782b905361
  router:
    resource: '%kernel.project_dir%/Configuration/routing_prod.yml'
    strict_requirements: true
