imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

# These aliases allow retrieving non-public services via the container in the integration tests.
# See https://symfony.com/doc/current/service_container/alias_private.html#aliasing for details.
services:
    test.AdministratorRepository:
        alias: PhpList\PhpList4\Domain\Repository\Identity\AdministratorRepository
    test.AdministratorTokenRepository:
        alias: PhpList\PhpList4\Domain\Repository\Identity\AdministratorTokenRepository
