imports:
  - { resource: "services.yml" }

framework:
  test: ~
  session:
    storage_id: session.storage.mock_file
  profiler:
    collect: false
  secret: a95c530a7af5f492a74499e70578d150d9c7e737
  router:
    resource: '%kernel.project_dir%/Configuration/routing_test.yml'
    strict_requirements: true
