services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    application.structure:
        class: PhpList\PhpList4\Core\ApplicationStructure
        public: true

    security.hash_generator:
        class: PhpList\PhpList4\Security\HashGenerator
        public: true

    PhpList\PhpList4\Routing\ExtraLoader:
        tags: [routing.loader]

    PhpList\PhpList4\Domain\Repository\Identity\AdministratorRepository:
        class: PhpList\PhpList4\Domain\Repository\Identity\AdministratorRepository
        factory: Doctrine\ORM\EntityManagerInterface:getRepository
        arguments:
            - PhpList\PhpList4\Domain\Model\Identity\Administrator
        calls:
            - [injectHashGenerator, ['@security.hash_generator']]

    PhpList\PhpList4\Domain\Repository\Identity\AdministratorTokenRepository:
        class: PhpList\PhpList4\Domain\Repository\Identity\AdministratorTokenRepository
        factory: Doctrine\ORM\EntityManagerInterface:getRepository
        arguments:
            - PhpList\PhpList4\Domain\Model\Identity\AdministratorToken
